config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/haddocking/benchmark-tools:
      branch: main
      repo: https://github.com/haddocking/benchmark-tools
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/haddocking/benchmark-tools git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-purple-uakari.sh
        container: qc.acc_wiggy-lilac-lion
  QC.Doc:
    repos:
      github.com/haddocking/benchmark-tools find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-alizarin-tzu.sh
        container: qc.doc_skinny-lime-clam
      github.com/haddocking/benchmark-tools git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-turquoise-guppy.sh
        container: qc.doc_messy-magenta-forest
      github.com/haddocking/benchmark-tools markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-taupe-donkey.sh
        container: qc.doc_snippy-cobalt-shrew
  QC.Lic:
    repos:
      github.com/haddocking/benchmark-tools licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-indigo-dog.sh
        container: qc.lic_frumpy-dandelion-caracal
  QC.Sec:
    repos:
      github.com/haddocking/benchmark-tools gosec:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-olive-hare.sh
        container: qc.sec_boozy-magnolia-lionfish
  QC.Sty:
    repos:
      github.com/haddocking/benchmark-tools staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-dandelion-bongo.sh
        container: qc.sty_slaphappy-green-beagle
  QC.Ver:
    repos:
      github.com/haddocking/benchmark-tools get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-carmine-forest.sh
        container: qc.ver_snappy-harlequin-cougar
timeout: 5400
