config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/haddocking/benchmark-tools:
      branch: main
      repo: https://github.com/haddocking/benchmark-tools
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/haddocking/benchmark-tools git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-xanthic-mist.sh
        container: qc.acc_stuffy-cerulean-macaque
  QC.Doc:
    repos:
      github.com/haddocking/benchmark-tools find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-scarlet-cheetah.sh
        container: qc.doc_tasty-pink-ferret
      github.com/haddocking/benchmark-tools git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-lime-liger.sh
        container: qc.doc_nerdy-ochre-fox
      github.com/haddocking/benchmark-tools markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-aquamarine-zebra.sh
        container: qc.doc_leaky-malachite-numbat
  QC.Lic:
    repos:
      github.com/haddocking/benchmark-tools licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-rust-harrier.sh
        container: qc.lic_tacky-ecru-panda
  QC.Sec:
    repos:
      github.com/haddocking/benchmark-tools gosec:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-magnolia-chameleon.sh
        container: qc.sec_skanky-thistle-mau
  QC.Sty:
    repos:
      github.com/haddocking/benchmark-tools staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-ultramarine-foxhound.sh
        container: qc.sty_foggy-gold-pig
  QC.Ver:
    repos:
      github.com/haddocking/benchmark-tools get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-purple-emu.sh
        container: qc.ver_trippy-ruby-lion
timeout: 5400
