config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/haddocking/benchmark-tools:
      branch: main
      repo: https://github.com/haddocking/benchmark-tools
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/haddocking/benchmark-tools git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-grey-dugong.sh
        container: qc.acc_woozy-alizarin-dog
  QC.Doc:
    repos:
      github.com/haddocking/benchmark-tools find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-peach-mammoth.sh
        container: qc.doc_crappy-flax-dog
      github.com/haddocking/benchmark-tools git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-jade-buffalo.sh
        container: qc.doc_scanty-russet-rabbit
      github.com/haddocking/benchmark-tools markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-cardinal-albatross.sh
        container: qc.doc_geeky-wisteria-hyena
  QC.Lic:
    repos:
      github.com/haddocking/benchmark-tools licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-ultramarine-cattle.sh
        container: qc.lic_greasy-lime-otter
  QC.Sec:
    repos:
      github.com/haddocking/benchmark-tools gosec:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-azure-drever.sh
        container: qc.sec_fuzzy-crimson-scorpion
  QC.Sty:
    repos:
      github.com/haddocking/benchmark-tools staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-ecru-hummingbird.sh
        container: qc.sty_ugly-green-dormouse
  QC.Ver:
    repos:
      github.com/haddocking/benchmark-tools get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-aqua-cichlid.sh
        container: qc.ver_hasty-ultramarine-squirrel
timeout: 5400
